from django.conf import settings

__all__ = ['ModeratedModelMixin']


class ModeratedModelMixin(object):
    MODERATION_ACTIVE = settings.MODERATION_STATUS_ACTIVE
    MODERATION_BANNED_TEMPORARILY = settings.MODERATION_STATUS_BANNED_TEMPORARILY
    MODERATION_BANNED_PERMANENTLY = settings.MODERATION_STATUS_BANNED_PERMANENTLY
    MODERATION_BANNED_AUTO = settings.MODERATION_STATUS_BANNED_AUTO
    MODERATION_STATUSES = settings.MODERATION_STATUSES
