# Generated by Django 2.1.2 on 2019-07-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profanity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Normalizes form of profanity word')),
            ],
            options={
                'verbose_name': 'Profanity',
                'verbose_name_plural': 'Profanities',
            },
        ),
    ]
