# Generated by Django 2.1.2 on 2019-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anti_profanity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profanity',
            name='lang',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
    ]
